version: '3.1'

networks:
    semi:
        name: semi
        driver: bridge

services:
    frontend:
        container_name: frontend
        build:
            dockerfile: Dockerfile
            context: ./Frontend/cerberusPortal
        ports:
            - 80:80
        networks:
            - semi
