version: '3'
services:
  base:
    image: "mysql"
    container_name: 'MYSQL_Base'
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    volumes:
      - base:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  base:
